### ISSUE TITLE
An Imageanalysis model kills GAMA

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.experimental#39]
When I launch the model  `analyseWebcamImage.gaml` on the last version of GAMA source (2024-06), GAMA suddenly quits with the simple message iin the Eclipse console:
```
objc[60863]: Class _TtC18videocapture_arm6419VideoCaptureSession is implemented in both /Users/benoitgaudou/Library/Caches/JNA/temp/jna18064306551733465270.tmp (0x338b58c58) and /Users/benoitgaudou/Library/Caches/JNA/temp/jna14458365992940220760.tmp (0x338b90c58). One of the two will be used. Which one is undefined.

```

**Comment by lesquoyb** [comment]
I installed it on 1.9.3 release and gama crashes with this in the log file:
```
!SESSION 2024-02-27 15:01:59.940 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=17.0.8.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @noDefault

!ENTRY org.eclipse.osgi 4 0 2024-02-27 15:02:06.639
!MESSAGE An error occurred while automatically activating bundle msi.gama.core (17).
!STACK 0
org.osgi.framework.BundleException: Exception in msi.gama.common.Activator.start() of bundle msi.gama.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.NoSuchMethodError: 'void gaml.additions.imageanalysis.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.imageanalysis.GamlAdditions.initializeOperator(GamlAdditions.java:69)
	at gaml.additions.imageanalysis.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 35 more
Root exception:
java.lang.NoSuchMethodError: 'void gaml.additions.imageanalysis.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.imageanalysis.GamlAdditions.initializeOperator(GamlAdditions.java:69)
	at gaml.additions.imageanalysis.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

!ENTRY org.eclipse.osgi 4 0 2024-02-27 15:02:06.645
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: msi/gama/common/preferences/GamaPreferenceStore
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle msi.gama.core (17).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more
Caused by: org.osgi.framework.BundleException: Exception in msi.gama.common.Activator.start() of bundle msi.gama.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 28 more
Caused by: java.lang.NoSuchMethodError: 'void gaml.additions.imageanalysis.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.imageanalysis.GamlAdditions.initializeOperator(GamlAdditions.java:69)
	at gaml.additions.imageanalysis.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 35 more
```

When manually removing the plugin I still got the same crash and similar log file but for the webcam plugin (which imageanalysis depends on):
```
!SESSION 2024-02-27 15:20:51.214 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=17.0.8.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @noDefault

!ENTRY org.eclipse.osgi 4 0 2024-02-27 15:20:54.585
!MESSAGE An error occurred while automatically activating bundle msi.gama.core (17).
!STACK 0
org.osgi.framework.BundleException: Exception in msi.gama.common.Activator.start() of bundle msi.gama.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.NoSuchMethodError: 'void gaml.additions.webcam.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.webcam.GamlAdditions.initializeOperator(GamlAdditions.java:66)
	at gaml.additions.webcam.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 35 more
Root exception:
java.lang.NoSuchMethodError: 'void gaml.additions.webcam.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.webcam.GamlAdditions.initializeOperator(GamlAdditions.java:66)
	at gaml.additions.webcam.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

!ENTRY org.eclipse.osgi 4 0 2024-02-27 15:20:54.595
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: msi/gama/common/preferences/GamaPreferenceStore
	at msi.gama.application.workspace.WorkspacePreferences.isRememberWorkspace(WorkspacePreferences.java:69)
	at msi.gama.application.Application.checkWorkspace(Application.java:228)
	at org.eclipse.swt.widgets.Display.lambda$1(Display.java:4841)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4803)
	at org.eclipse.swt.widgets.Display.syncCall(Display.java:4839)
	at msi.gama.application.Application.start(Application.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle msi.gama.core (17).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more
Caused by: org.osgi.framework.BundleException: Exception in msi.gama.common.Activator.start() of bundle msi.gama.core.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 28 more
Caused by: java.lang.NoSuchMethodError: 'void gaml.additions.webcam.GamlAdditions._operator(java.lang.String[], java.lang.reflect.Executable, int[], java.lang.Object, boolean, int, int, int, int, msi.gaml.compilation.GamaGetter, boolean)'
	at gaml.additions.webcam.GamlAdditions.initializeOperator(GamlAdditions.java:66)
	at gaml.additions.webcam.GamlAdditions.initialize(GamlAdditions.java:59)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$11(GamaBundleLoader.java:464)
	at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:156)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
	at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:230)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:131)
	at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:193)
	at msi.gama.common.Activator.start(Activator.java:28)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 35 more
```
